---
user_group: "{{ jenkins_user_group }}"
user_name: "{{ jenkins_user_name }}"
jenkins_user_name: jenkins
jenkins_user_group: jenkins
jenkins_agent_dir: /opt/jenkins_agent/
docker_user: dervish
version_codename: jammy
